export const ChallengeTypes = {
  GET_CHALLENGE: "GET_CHALLENGE",
  GET_CHALLENGES: "GET_CHALLENGES",
  CHALLENGE_LOADED: "CHALLENGE_LOADED",
  CHALLENGES_LOADED: "CHALLENGES_LOADED",
  CHALLENGE_DELETE: "CHALLENGE_DELETE",
  CLEAR_CHALLENGES: "CLEAR_CHALLENGES",
  CHALLENGE_ERROR: "CHALLENGE_ERROR",
};
