export const TeamTypes = {
  GET_TEAM: "GET_TEAM",
  TEAM_LOADED: "TEAM_LOADED",
  GET_TEAMS: "GET_TEAMS",
  TEAMS_LOADED: "TEAMS_LOADED",
  UPDATE_TEAM: "UPDATE_TEAM",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_DELETE: "TEAM_DELETE",
  REGISTER_TEAM: "REGISTER_TEAM",
  TEAM_REGISTERED: "TEAM_REGISTERED",
  CLEAR_TEAMS: "CLEAR_TEAMS",
  TEAM_ERROR: "TEAM_ERROR",

  ADD_SCORE: "ADD_SCORE",
  UPDATE_SCORE: "UPDATE_SCORE",
  SCORE_SUCCESS: "SCORE_SUCCESS",
  DELETE_SCORE: "DELETE_SCORE",
};
