export const UserTypes = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_REQUEST_SUCCESS: "AUTH_REQUEST_SUCCESS",

  AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",

  AUTH_REGISTER_REQUEST: "AUTH_REGISTER_REQUEST",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",

  AUTH_USER_LOAD_REQUEST: "AUTH_USER_LOAD_REQUEST",
  AUTH_USER_LOADED: "AUTH_USER_LOADED",

  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_ERROR: "AUTH_ERROR",

  GET_USER: "GET_USER",
  USER_LOADED: "USER_LOADED",
  GET_USERS: "GET_USERS",
  USERS_LOADED: "USERS_LOADED",
  USER_DELETE: "USER_DELETE",
  CLEAR_USER: "CLEAR_USER",
  USER_ERROR: "USER_ERROR",
};
